spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_quartz?useSSL=FALSE&allowMultiQueries=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: '!@#$1234Abcd'
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
      additional-paths: mapper



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.niu.springbootquartz.model
  cache-enabled: true
  default-statement-timeout: 10000
  map-underscore-to-camel-case: true
  use-generated-keys: true
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check



logging:
  level:
    com.niu.springbootquartz.mapper: debug